name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
    
permissions:
  contents: write
  
jobs:
  deploy-to-github-pages:
    # Use the latest Ubuntu image to run steps on
    runs-on: ubuntu-latest

    steps:
      # Uses GitHub's checkout action to checkout code from the main branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up .NET SDK 
      # see setup-dotnet@v2 https://github.com/actions/setup-dotnet/releases
      # see SKDs! from https://versionsof.net/core/) 
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.0.303'

      - name: Test 
        run: dotnet test --verbosity diagnostic
        
      # Publishes Blazor project to the release folder
      - name: Publish .NET Core Project
        run: dotnet publish test.csproj -c Release -o release --nologo

    # changes the base-tag in index.html from '/' to 'testpages' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to testpages
        run: sed -i 's/<base href="\/" \/>/<base href="\/test\/" \/>/g' release/wwwroot/index.html

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Add .nojekyll file to tell GitHub Pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
  
      # Commits wwwroot to GitHub Pages (https://github.com/marketplace/actions/deploy-to-github-pages)
      # was /wwwroot
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release
